### ISSUE TITLE
Expose missing services closer to their dependent definitions

### ISSUE THREAD

**Issue by patroza** [effect-app/libs#107]
Right now, if you miss specifying a dependency, you get an error at the root main function, which is far away from the Service or Controller that uses the dependency. Depending how many changes you did, or what package got updated, you might have a hard time tracking where you are missing the dependency.

e.g
- Service uses AnotherService, but forgets to add AnotherService to dependencies
  https://github.com/patroza/effect/pull/13/files
  - I like the idea of having Effect.Service, have a default `strict: true`, that you can bail out of with `strict: false`. When strict, defining a service should give an error when you did not provide all services. (Mike does not agree)
- Controllers uses Service, but forgets to add Service to the dependencies (first array)
  - Same as with the strict Service idea; demand the deps to be provided, unless `strict: false`
  - 
  
We could also leverage `satisfies` somehow. Like `satisfies Layer<any,any,never>`

**Comment by enricopolanski** [comment]
Sounds reasonable.

**Comment by patroza** [comment]
Will apply these for now, but instead of a strict true/false, for the near future, I would consider a whitelist of dependencies you want to pass through, it will still provide meaningful protection, instead of completely opt out.

**Comment by patroza** [comment]
Implemented in https://github.com/effect-app/libs/commit/565d6783d2e491636d0f356bd32bd61ab6d728c4

**Comment by patroza** [comment]
I think we can make things nicer for the controller, if we would use an option object instead of positional args, but it would cause an extra indent for all the action handlers which I’m not really willing to pay. But if I can shave off one, maybe I’ll consider it

**Comment by patroza** [comment]
Got an updated API for controllers, which makes it even more similar to Effect.Service, and has the same benefits of the dependencies error reporting, without adding additional indentation level, with only minor adjustments:
https://github.com/effect-app/sample/compare/29762037f9ae03099cf1082f099afce508948f30..2d3da5d50d9c3aa1b1d5faae956618f456656ac0
<img width="746" alt="Screenshot 2024-11-03 at 21 27 07" src="https://github.com/user-attachments/assets/f704dbcc-3c28-49ed-ada3-f6f44d8c17bf">

**Comment by patroza** [comment]
> Implemented in [565d678](https://github.com/effect-app/libs/commit/565d6783d2e491636d0f356bd32bd61ab6d728c4)

Finalised in https://github.com/effect-app/libs/commit/01f531e80354be77cbc917ff82557e30cbe981b5
