### ISSUE TITLE
Refine nullable fields to non nullable when the query confirms it

### ISSUE THREAD

**Issue by patroza** [effect-app/libs#87]
like https://github.com/effect-ts-app/libs/commit/4ab14def7441d084e8ff09db2db18b0473842cc0
but for `where("x", "neq", null)`

**Comment by jfet97** [comment]
Should `where("x", "neq", null)` filter out `undefined` too?

**Comment by patroza** [comment]
> Should `where("x", "neq", null)` filter out `undefined` too?

no, `undefined` and `null` are not the same and `undefined` is generally not a state we support in the storage model.
only for just in time migrations, but are then filled by the database via config.defaultValues (e.g `defaultValues: { x: null }`)

**Comment by jfet97** [comment]
#105
