### ISSUE TITLE
Express more complex queries on simple array members

### ISSUE THREAD

**Issue by patroza** [effect-app/libs#95]
```ts
{
   indexes: string[]
}
query(Q.where("indexes.-1", "startsWith", "a"))
```

(right now `-1` means "any")

we have it already for complex types:
```ts
{
   indexes: { name: string }. []
}
query(Q.where("indexes.-1.name", "startsWith", "a")) 
```

**Comment by jfet97** [comment]
I don't get the value of doing this, could you please fix the second example and/or provide a more meaningful example?

**Comment by jfet97** [comment]
https://github.com/macs-holding/configurator/blob/5e9204e8a7fe684485c9999d061b07511aafa247/api/src/services/Configurators.ts#L39

now imagine shops is a string[] instead of object
right now we can't eq, neq, startsWith, endsWith etc it's elements

**Comment by jfet97** [comment]
<img width="1099" alt="image" src="https://github.com/user-attachments/assets/506d6ddd-262a-42b7-aabe-2723923f76c7">

**Comment by patroza** [comment]
already works apparently... nothing to see here :D
